name: Linting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: iCrawl/action-eslint@v1
        with:
          # Custom glob to overwrite which files to lint.
          custom-glob: src

